In [ ]:
import numpy as np

In [ ]:
# creating arrays
# One dimensional array
arr1= np.array([12,32,43])

# Two dimensional array
arr2=np.array([[12,23,43],[45,11,33]])

# three dimensional array
arr3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr1)
print(arr2)
print(arr3)

[12 32 43]
[[12 23 43]
 [45 11 33]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:

#Special arrays
#zeros
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#ones
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2) # 3 denotes number of rows, 2 denotes number of columns

array([[0.7553548 , 0.21920841],
       [0.58141237, 0.87097398],
       [0.52905765, 0.72348693]])

In [ ]:
np.random.randint(1,10,50) #1 denotes starting range, 10 denotes last range, 50 denotes number of values

array([7, 6, 8, 7, 6, 5, 4, 2, 3, 9, 7, 3, 2, 1, 8, 7, 2, 1, 2, 8, 9, 6,
       7, 3, 6, 7, 1, 9, 9, 7, 7, 1, 9, 5, 4, 1, 6, 9, 6, 4, 6, 5, 4, 9,
       9, 2, 8, 1, 3, 9])

In [ ]:
np.random.randint(2,40,(5,5))

array([[20, 39, 17,  6,  7],
       [27,  6, 28, 10,  8],
       [12, 18,  5, 19, 23],
       [20, 28, 26, 29,  3],
       [17, 38, 23,  7,  9]])

In [ ]:
#arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
#Array attributes
arr1.shape

(3,)

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3.shape

(2, 2, 2)

In [ ]:
arr2.ndim # check the dimension of the array

2

In [ ]:
arr2.size # number of elements in the array

6

In [ ]:
arr3.dtype # checks the datatype of the array

dtype('int64')

In [ ]:
#Indexing in arrays
arr3[0][1][0]

np.int64(3)

In [ ]:
arr2.reshape(3,2)

array([[12, 23],
       [43, 45],
       [11, 33]])

In [ ]:
arr2.reshape(1,6)

array([[12, 23, 43, 45, 11, 33]])

In [ ]:
arr2.reshape(6,1)

array([[12],
       [23],
       [43],
       [45],
       [11],
       [33]])

In [ ]:
#flatten
arr2.flatten()

array([12, 23, 43, 45, 11, 33])

In [ ]:
# Mean, median, variance, standard deviation
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.max(arr1))
print(np.argmax(arr1)) # index of the array where maximum value is present
print(np.sort(arr1))

29.0
32.0
12.832251036613439
164.66666666666666
43
2
[12 32 43]


In [ ]:
# Broadcasting
#arr with dim 2,3
arr=np.array([3,2,9,4])
print(arr*3)

[ 9  6 27 12]
